# Generated by Django 4.2.30 on 2026-07-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline on the slide.', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Short tagline below the title.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional caption text on the slide.')),
                ('image_url', models.URLField(help_text='Background image URL for the slide.')),
                ('link_url', models.CharField(blank=True, help_text='Optional CTA link (e.g. /contact/ or #services).', max_length=300)),
                ('link_text', models.CharField(blank=True, default='Learn More', help_text='CTA button label.', max_length=80)),
                ('category', models.CharField(choices=[('service', 'Service'), ('promotion', 'Promotion / Ad')], default='service', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Ad',
                'verbose_name_plural': 'Home Ads',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
