# Generated by Django 4.2.30 on 2026-07-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_emailsubscription_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(help_text='Job title, e.g. Chief Executive Officer', max_length=120)),
                ('department', models.CharField(blank=True, help_text='Short label, e.g. Managing Director', max_length=80)),
                ('bio', models.TextField(blank=True, help_text='Short description shown on the About page.')),
                ('photo', models.ImageField(blank=True, help_text='Upload a square portrait photo (recommended 400×400 or larger).', null=True, upload_to='team/')),
                ('initials', models.CharField(blank=True, help_text='Fallback initials when no photo is uploaded (e.g. CEO).', max_length=4)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
