# Generated by Django 4.2.30 on 2026-07-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a cover image from your computer.', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste an external image URL. Upload takes priority if both are set.'),
        ),
    ]
